# University Student Data — Cleaning & Analysis

This notebook builds a small student dataset, cleans the missing values,
and then runs a few summary analyses on it.

**Note on running this notebook:** the cells below are split one-task-per-cell
(matching the assignment's numbered steps) on purpose, so each transformation
is visible separately. They must be run **in order, top to bottom** (or via
*Run All*), because each cleaning step modifies `university_df` in place and
later cells depend on the result of earlier ones.

## Setup: create the dataset

In [1]:
# Import required libraries
import pandas as pd
import numpy as np

# Create the university student dataset
university_df = pd.DataFrame({
    "student_id": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    "name": [
        "Abel", "Sara", None, "John", "Marta",
        None, "David", "Helen", "Tom", None
    ],
    "department": [
        "CS", "IT", "CS", None, "SE",
        "IT", "SE", None, "CS", "IT"
    ],
    "gpa": [
        3.5, 3.8, np.nan, 2.9, 3.7,
        np.nan, 3.2, 3.4, 3.9, np.nan
    ],
    "scholarship": [
        5000, np.nan, 3000, 2000, np.nan,
        4000, 3500, np.nan, 5000, np.nan
    ]
})

university_df

   student_id   name department  gpa  scholarship
0         201   Abel         CS  3.5       5000.0
1         202   Sara         IT  3.8          NaN
2         203    NaN         CS  NaN       3000.0
3         204   John        NaN  2.9       2000.0
4         205  Marta         SE  3.7          NaN
5         206    NaN         IT  NaN       4000.0
6         207  David         SE  3.2       3500.0
7         208  Helen        NaN  3.4          NaN
8         209    Tom         CS  3.9       5000.0
9         210    NaN         IT  NaN          NaN

In [2]:
# Check dataset structure and information
university_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   10 non-null     int64
 1   name         7 non-null      str
 2   department   8 non-null      str
 3   gpa          7 non-null      float64
 4   scholarship  6 non-null      float64
dtypes: float64(2), int64(1), str(2)
memory usage: 532.0 bytes

## Data Cleaning

In [3]:
# 1. Count missing values in each column
missing_count = university_df.isnull().sum()
print("Missing values per column:")
missing_count

Missing values per column:

student_id     0
name           3
department     2
gpa            3
scholarship    4
dtype: int64

In [4]:
# 2. Calculate missing value percentage for each column
missing_percentage = (missing_count / len(university_df)) * 100
print("Missing value percentage (%) per column:")
missing_percentage

Missing value percentage (%) per column:

student_id      0.0
name           30.0
department     20.0
gpa            30.0
scholarship    40.0
dtype: float64

In [5]:
# 3. Replace missing names with "Unknown"
university_df["name"] = university_df["name"].fillna("Unknown")
university_df

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          NaN
2         203  Unknown         CS  NaN       3000.0
3         204     John        NaN  2.9       2000.0
4         205    Marta         SE  3.7          NaN
5         206  Unknown         IT  NaN       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen        NaN  3.4          NaN
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  NaN          NaN

In [6]:
# 4. Replace missing departments using the mode (most common department)
university_df["department"] = university_df["department"].fillna(
    university_df["department"].mode()[0]
)
university_df

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          NaN
2         203  Unknown         CS  NaN       3000.0
3         204     John         CS  2.9       2000.0
4         205    Marta         SE  3.7          NaN
5         206  Unknown         IT  NaN       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen         CS  3.4          NaN
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  NaN          NaN

In [7]:
# 5. Replace missing GPA values using the median GPA
university_df["gpa"] = university_df["gpa"].fillna(
    university_df["gpa"].median()
)
university_df

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          NaN
2         203  Unknown         CS  3.5       3000.0
3         204     John         CS  2.9       2000.0
4         205    Marta         SE  3.7          NaN
5         206  Unknown         IT  3.5       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen         CS  3.4          NaN
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          NaN

In [8]:
# 6. Replace missing scholarship values with zero
university_df["scholarship"] = university_df["scholarship"].fillna(0)
university_df

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          0.0
2         203  Unknown         CS  3.5       3000.0
3         204     John         CS  2.9       2000.0
4         205    Marta         SE  3.7          0.0
5         206  Unknown         IT  3.5       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen         CS  3.4          0.0
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          0.0

## Data Analysis

In [9]:
# 7. Count students by department
department_counts = university_df["department"].value_counts()
print("Students by department:")
print(department_counts)

Students by department:
department
CS    5
IT    3
SE    2
Name: count, dtype: int64

In [10]:
# 8. Count scholarship recipients
num_scholarship_recipients = (university_df["scholarship"] > 0).sum()
print("Number of scholarship recipients:", num_scholarship_recipients)

Number of scholarship recipients: 6

In [11]:
# 9. Find the highest GPA
highest_gpa = university_df["gpa"].max()
print("Highest GPA:", highest_gpa)

Highest GPA: 3.9

In [12]:
# 10. Find the lowest GPA
lowest_gpa = university_df["gpa"].min()
print("Lowest GPA:", lowest_gpa)

Lowest GPA: 2.9

In [13]:
# 11. Calculate the average GPA
average_gpa = university_df["gpa"].mean()
print("Average GPA:", round(average_gpa, 2))

Average GPA: 3.49

In [14]:
# 12. Calculate the total scholarship amount awarded
total_scholarship = university_df["scholarship"].sum()
print("Total scholarship amount:", total_scholarship)

Total scholarship amount: 22500.0

## Final Cleaned Dataset

In [15]:
# Final check: the fully cleaned dataset
print("Final cleaned dataset:")
university_df

Final cleaned dataset:

   student_id     name department  gpa  scholarship
0         201     Abel         CS  3.5       5000.0
1         202     Sara         IT  3.8          0.0
2         203  Unknown         CS  3.5       3000.0
3         204     John         CS  2.9       2000.0
4         205    Marta         SE  3.7          0.0
5         206  Unknown         IT  3.5       4000.0
6         207    David         SE  3.2       3500.0
7         208    Helen         CS  3.4          0.0
8         209      Tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          0.0